### ISSUE TITLE
Deploy empirica using GitHub Action

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#11]
As a research coordinator, I want to be able to deploy the Empirica experiment on a cloud hosting provider using a GitHub action from this repository, so that I can ensure that the deployed version is up to date with minimal effort or opportunity for mistakes.

## Resources:
- Similar to: https://github.com/Watts-Lab/turk-interface/pull/8
- Using services decided here: https://github.com/Watts-Lab/deliberation-empirica/issues/16
- Available at URL decided in: https://github.com/Watts-Lab/deliberation_project/issues/29
- Getting access tokens: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

## Todo:
- [x] Authenticate to AWS and get key/id for use in deploy actions
- [ ] #21
- [ ] https://github.com/Watts-Lab/deliberation-empirica/issues/26 as part of deploy workflow
- [ ] #33
- [ ] Update the production dockerfile to use the correct build/serve commands (need to find out what these are from nicolas)
- [ ] Turn off the developer conveniences - such as the link to the admin panel, and the elephant button.
- [ ] Set up HTTPS
- [ ] Test that the admin console is available at the correct URL at the end of the deploy action

## This issue can be closed when:
- [ ] By triggering a GitHub action, I can launch the Empirica code in this repository on our cloud hosting provider
- [ ] I can log into the Empirica admin console on the server at our own URL
- [ ] If an instance of the server is already running, I don't launch a second by accident. (Need to determine if the right thing to do is to replace the existing instance, to throw an error, or something else. I am not a DevOps person...)
- [ ] The action is well-documented so that it can be understood and maintained by other developers.

@markwhiting @sumants-dev @rivera-lanasm, can you help me identify a strategy for doing this?

**Comment by JamesPHoughton** [comment]
Using instructions from here: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services used the IAM console on amazon to create a security policy for access to AWS elastic beanstalk (called `deliberation-empirica`), and then a role that could be used for deploying to elastic beanstalk. 

Then, used the [aws-actions/configure-aws-credentials](https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions) action to get credentials through this system. In theory this should allow connections from this repo without needing to store long-term secrets.

**Comment by JamesPHoughton** [comment]
Also this from the AWS Console:
![image](https://user-images.githubusercontent.com/4304478/166952699-ae2593ba-0472-4ac9-8da1-c26474dfd39c.png)

**Comment by JamesPHoughton** [comment]
I'm updating the trust policy to deploy from any branch:
```
"token.actions.githubusercontent.com:sub": "repo:Watts-Lab/deliberation-empirica:ref:refs/heads/*"
```
When we think we've worked out the deploy issues, we should change this so that we only deploy from 'main', most likely.

**Comment by JamesPHoughton** [comment]
The current deploy process is for DigitalOcean (https://cloud.digitalocean.com/apps?i=dc840e) to pull from `main` when changes are made, and deploy automatically. This seems to be working for now?
